# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Elm
      uses: justgook/setup-elm@v1
      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Builds the elm app
    - name: Build Elm app
      run: |
        echo Building Elm app
        mkdir public
        elm make --output=public/index.html src/Main.elm
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: elm-app
        path: public

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
      - name: Download elm app
        uses: actions/download-artifact@v1
        with:
          name: elm-app
          path: public
      # Build, transpile etc.
      - name: Upload static assets to Dark canvas
        uses: gregbrimble/dark-static-assets-action@v1.0.0
        with:
          user: ${{ secrets.DARK_USER }}
          password: ${{ secrets.DARK_PASSWORD }}
          canvas: dota-dashboad
          paths: public
